import type { TemplateSet, PreviewTemplate } from "@/types";
import { CANVAS_WIDTH, CANVAS_HEIGHT } from "../placeholders";

// Design tokens for E-commerce Showcase - Continuous Flow Design
// All screenshots maintain -15° angle, creating a visual ribbon when swiping
const designTokens = {
  primaryColor: "#ffffff",
  secondaryColor: "rgba(255, 255, 255, 0.8)",
  accentColor: "#f43f5e", // Rose
  fontFamily: "system-ui, -apple-system, sans-serif",
};

// Consistent angle across ALL previews for continuous flow effect
const FLOW_ANGLE = -15;

// Screenshot flows from right to left across previews
// Position shifts create the "ribbon" effect when swiping
const FLOW_POSITIONS = {
  // Preview 1-2: Screenshot entering from right
  enterRight: { left: 1050, top: 1650 },
  // Preview 3-4: Screenshot moving to center-right
  centerRight: { left: 850, top: 1600 },
  // Preview 5-6: Screenshot at center
  center: { left: CANVAS_WIDTH / 2, top: 1580 },
  // Preview 7-8: Screenshot moving to center-left
  centerLeft: { left: 440, top: 1600 },
  // Preview 9-10: Screenshot exiting to left
  exitLeft: { left: 240, top: 1650 },
};

// Preview 1: Flow Entry - Screenshot entering from right edge
const flowEntryTemplate: PreviewTemplate = {
  id: "ecs-flow-1",
  name: "Flow: Welcome",
  description: "Opening shot - screenshot flows in from right",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(135deg, #0f0f0f 0%, #1a1a1a 100%)",
  placeholders: [
    {
      id: "flow-1-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-home.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Large watermark text - creates depth
      {
        type: "textbox",
        text: "SHOP",
        fontSize: 320,
        fontWeight: "900",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.03)",
        left: -50,
        top: 400,
        width: 1000,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      // Main headline
      {
        type: "textbox",
        text: "Welcome to",
        fontSize: 52,
        fontWeight: "400",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.secondaryColor,
        left: 90,
        top: 200,
        width: 600,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "The Future",
        fontSize: 130,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: 90,
        top: 260,
        width: 800,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "of Shopping",
        fontSize: 130,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.accentColor,
        left: 90,
        top: 390,
        width: 900,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      // Screenshot - entering from right, partially visible
      {
        type: "image",
        src: "/placeholders/screenshots/app-home.svg",
        left: FLOW_POSITIONS.enterRight.left,
        top: FLOW_POSITIONS.enterRight.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(244, 63, 94, 0.4)",
          blur: 150,
          offsetX: -60,
          offsetY: 60,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-1-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 2: Flow Continue - Screenshot more visible
const flowContinueTemplate: PreviewTemplate = {
  id: "ecs-flow-2",
  name: "Flow: Discover",
  description: "Screenshot continues flowing in",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(145deg, #18181b 0%, #27272a 100%)",
  placeholders: [
    {
      id: "flow-2-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-dashboard.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Accent line - visual continuity
      {
        type: "rect",
        left: 90,
        top: 200,
        width: 80,
        height: 6,
        rx: 3,
        ry: 3,
        fill: designTokens.accentColor,
        originX: "left",
        originY: "top",
      },
      // Label
      {
        type: "textbox",
        text: "DISCOVER",
        fontSize: 28,
        fontWeight: "600",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.accentColor,
        left: 90,
        top: 240,
        width: 400,
        textAlign: "left",
        originX: "left",
        originY: "top",
        charSpacing: 200,
      },
      // Headline
      {
        type: "textbox",
        text: "Millions of",
        fontSize: 110,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: 90,
        top: 310,
        width: 700,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Products",
        fontSize: 110,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.secondaryColor,
        left: 90,
        top: 430,
        width: 600,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      // Screenshot - flowing in more
      {
        type: "image",
        src: "/placeholders/screenshots/app-dashboard.svg",
        left: FLOW_POSITIONS.centerRight.left,
        top: FLOW_POSITIONS.centerRight.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(244, 63, 94, 0.35)",
          blur: 140,
          offsetX: -50,
          offsetY: 55,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-2-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 3: Flow Center Right - Categories
const flowCategoriesTemplate: PreviewTemplate = {
  id: "ecs-flow-3",
  name: "Flow: Categories",
  description: "Browse categories",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(160deg, #4c1d95 0%, #6d28d9 100%)",
  placeholders: [
    {
      id: "flow-3-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-list.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Category count
      {
        type: "textbox",
        text: "500+",
        fontSize: 180,
        fontWeight: "900",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.1)",
        left: 90,
        top: 140,
        width: 500,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Categories",
        fontSize: 90,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: 90,
        top: 330,
        width: 600,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "to explore",
        fontSize: 90,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.5)",
        left: 90,
        top: 430,
        width: 500,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      // Screenshot - center right position
      {
        type: "image",
        src: "/placeholders/screenshots/app-list.svg",
        left: FLOW_POSITIONS.centerRight.left + 50,
        top: FLOW_POSITIONS.centerRight.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(109, 40, 217, 0.5)",
          blur: 140,
          offsetX: -45,
          offsetY: 50,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-3-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 4: Flow Center - Deals
const flowDealsTemplate: PreviewTemplate = {
  id: "ecs-flow-4",
  name: "Flow: Deals",
  description: "Flash deals and offers",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(150deg, #dc2626 0%, #ea580c 100%)",
  placeholders: [
    {
      id: "flow-4-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-home.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Discount badge
      {
        type: "rect",
        left: 90,
        top: 180,
        width: 180,
        height: 70,
        rx: 35,
        ry: 35,
        fill: "#ffffff",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "70% OFF",
        fontSize: 28,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: "#dc2626",
        left: 180,
        top: 200,
        width: 160,
        textAlign: "center",
        originX: "center",
        originY: "top",
      },
      // Headline
      {
        type: "textbox",
        text: "Flash",
        fontSize: 140,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: 90,
        top: 290,
        width: 500,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Deals",
        fontSize: 140,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.7)",
        left: 90,
        top: 430,
        width: 400,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      // Screenshot - approaching center
      {
        type: "image",
        src: "/placeholders/screenshots/app-home.svg",
        left: FLOW_POSITIONS.center.left + 100,
        top: FLOW_POSITIONS.center.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(0,0,0,0.5)",
          blur: 130,
          offsetX: -40,
          offsetY: 50,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-4-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 5: Flow Center - Wishlist (center position)
const flowWishlistTemplate: PreviewTemplate = {
  id: "ecs-flow-5",
  name: "Flow: Wishlist",
  description: "Save your favorites",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(160deg, #be185d 0%, #ec4899 100%)",
  placeholders: [
    {
      id: "flow-5-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-profile.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Heart symbol using text
      {
        type: "textbox",
        text: "♥",
        fontSize: 120,
        fontWeight: "400",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.2)",
        left: 90,
        top: 150,
        width: 150,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      // Headline
      {
        type: "textbox",
        text: "Save What",
        fontSize: 105,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: 90,
        top: 300,
        width: 600,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "You Love",
        fontSize: 105,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.6)",
        left: 90,
        top: 415,
        width: 500,
        textAlign: "left",
        originX: "left",
        originY: "top",
      },
      // Screenshot - at center
      {
        type: "image",
        src: "/placeholders/screenshots/app-profile.svg",
        left: FLOW_POSITIONS.center.left,
        top: FLOW_POSITIONS.center.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(236, 72, 153, 0.5)",
          blur: 140,
          offsetX: -35,
          offsetY: 50,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-5-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 6: Flow Center Left - Cart
const flowCartTemplate: PreviewTemplate = {
  id: "ecs-flow-6",
  name: "Flow: Cart",
  description: "Easy checkout experience",
  category: "device-showcase",
  deviceType: "both",
  background: "#0a0a0a",
  placeholders: [
    {
      id: "flow-6-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-dashboard.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Trust badge
      {
        type: "textbox",
        text: "SECURE CHECKOUT",
        fontSize: 24,
        fontWeight: "600",
        fontFamily: designTokens.fontFamily,
        fill: "#22c55e",
        left: CANVAS_WIDTH - 90,
        top: 200,
        width: 400,
        textAlign: "right",
        originX: "right",
        originY: "top",
        charSpacing: 150,
      },
      // Headline - right aligned for this one
      {
        type: "textbox",
        text: "One Tap",
        fontSize: 120,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: CANVAS_WIDTH - 90,
        top: 280,
        width: 600,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Checkout",
        fontSize: 120,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: "#22c55e",
        left: CANVAS_WIDTH - 90,
        top: 410,
        width: 600,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      // Screenshot - moving to center-left
      {
        type: "image",
        src: "/placeholders/screenshots/app-dashboard.svg",
        left: FLOW_POSITIONS.center.left - 100,
        top: FLOW_POSITIONS.center.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(34, 197, 94, 0.35)",
          blur: 140,
          offsetX: -30,
          offsetY: 50,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-6-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 7: Flow Left - Delivery
const flowDeliveryTemplate: PreviewTemplate = {
  id: "ecs-flow-7",
  name: "Flow: Delivery",
  description: "Fast shipping",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(145deg, #0d9488 0%, #14b8a6 100%)",
  placeholders: [
    {
      id: "flow-7-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-list.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Speed indicator
      {
        type: "textbox",
        text: "SAME DAY",
        fontSize: 28,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: "#fbbf24",
        left: CANVAS_WIDTH - 90,
        top: 200,
        width: 300,
        textAlign: "right",
        originX: "right",
        originY: "top",
        charSpacing: 150,
      },
      // Headline - right aligned
      {
        type: "textbox",
        text: "Lightning",
        fontSize: 110,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: CANVAS_WIDTH - 90,
        top: 280,
        width: 600,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Delivery",
        fontSize: 110,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.6)",
        left: CANVAS_WIDTH - 90,
        top: 400,
        width: 500,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      // Screenshot - center left
      {
        type: "image",
        src: "/placeholders/screenshots/app-list.svg",
        left: FLOW_POSITIONS.centerLeft.left,
        top: FLOW_POSITIONS.centerLeft.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(20, 184, 166, 0.5)",
          blur: 130,
          offsetX: -25,
          offsetY: 45,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-7-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 8: Flow Exit - Reviews
const flowReviewsTemplate: PreviewTemplate = {
  id: "ecs-flow-8",
  name: "Flow: Reviews",
  description: "Trusted by millions",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(160deg, #1e3a8a 0%, #3b82f6 100%)",
  placeholders: [
    {
      id: "flow-8-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-profile.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Stars
      {
        type: "textbox",
        text: "★★★★★",
        fontSize: 42,
        fontWeight: "400",
        fontFamily: designTokens.fontFamily,
        fill: "#fbbf24",
        left: CANVAS_WIDTH - 90,
        top: 180,
        width: 350,
        textAlign: "right",
        originX: "right",
        originY: "top",
        charSpacing: 30,
      },
      {
        type: "textbox",
        text: "4.9",
        fontSize: 160,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: CANVAS_WIDTH - 90,
        top: 240,
        width: 300,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      {
        type: "textbox",
        text: "from 500K+ reviews",
        fontSize: 36,
        fontWeight: "500",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.secondaryColor,
        left: CANVAS_WIDTH - 90,
        top: 420,
        width: 400,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      // Screenshot - exiting left
      {
        type: "image",
        src: "/placeholders/screenshots/app-profile.svg",
        left: FLOW_POSITIONS.centerLeft.left - 50,
        top: FLOW_POSITIONS.centerLeft.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(59, 130, 246, 0.5)",
          blur: 130,
          offsetX: -20,
          offsetY: 45,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-8-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 9: Flow Exit - Rewards
const flowRewardsTemplate: PreviewTemplate = {
  id: "ecs-flow-9",
  name: "Flow: Rewards",
  description: "Loyalty program",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(145deg, #b45309 0%, #f59e0b 100%)",
  placeholders: [
    {
      id: "flow-9-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-dashboard.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Multiplier
      {
        type: "textbox",
        text: "5X",
        fontSize: 200,
        fontWeight: "900",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.15)",
        left: CANVAS_WIDTH - 90,
        top: 120,
        width: 350,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      // Headline
      {
        type: "textbox",
        text: "Earn",
        fontSize: 120,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: CANVAS_WIDTH - 90,
        top: 320,
        width: 400,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Rewards",
        fontSize: 120,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.7)",
        left: CANVAS_WIDTH - 90,
        top: 450,
        width: 500,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      // Screenshot - almost exited
      {
        type: "image",
        src: "/placeholders/screenshots/app-dashboard.svg",
        left: FLOW_POSITIONS.exitLeft.left + 80,
        top: FLOW_POSITIONS.exitLeft.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(245, 158, 11, 0.5)",
          blur: 120,
          offsetX: -15,
          offsetY: 40,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-9-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 10: Flow Finale - CTA with screenshot exiting
const flowFinaleTemplate: PreviewTemplate = {
  id: "ecs-flow-10",
  name: "Flow: Download",
  description: "Final CTA - screenshot exits",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(180deg, #0f0f0f 0%, #171717 50%, #0f0f0f 100%)",
  placeholders: [
    {
      id: "flow-10-screenshot",
      name: "Screenshot",
      url: "/placeholders/screenshots/app-home.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Large background text
      {
        type: "textbox",
        text: "GO",
        fontSize: 400,
        fontWeight: "900",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(244, 63, 94, 0.05)",
        left: 300,
        top: 180,
        width: 800,
        textAlign: "center",
        originX: "left",
        originY: "top",
      },
      // CTA headline - right side
      {
        type: "textbox",
        text: "Start",
        fontSize: 130,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: CANVAS_WIDTH - 90,
        top: 250,
        width: 500,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Shopping",
        fontSize: 130,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.accentColor,
        left: CANVAS_WIDTH - 90,
        top: 385,
        width: 600,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      // Platform text
      {
        type: "textbox",
        text: "Free on iOS & Android",
        fontSize: 36,
        fontWeight: "500",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.secondaryColor,
        left: CANVAS_WIDTH - 90,
        top: 550,
        width: 500,
        textAlign: "right",
        originX: "right",
        originY: "top",
      },
      // Screenshot - exiting left
      {
        type: "image",
        src: "/placeholders/screenshots/app-home.svg",
        left: FLOW_POSITIONS.exitLeft.left,
        top: FLOW_POSITIONS.exitLeft.top,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: FLOW_ANGLE,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(244, 63, 94, 0.5)",
          blur: 150,
          offsetX: -10,
          offsetY: 45,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flow-10-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Complete E-commerce Showcase - Continuous Flow Design
export const ecommerceShowcaseSet: TemplateSet = {
  id: "ecommerce-showcase",
  name: "E-commerce Showcase",
  description: "Continuous flow design - screenshots glide across previews creating a cinematic ribbon effect",
  category: "feature-focused",
  appStoreCategories: ["ecommerce", "shopping"],
  deviceType: "both",
  previewCount: 10,
  templates: [
    flowEntryTemplate,
    flowContinueTemplate,
    flowCategoriesTemplate,
    flowDealsTemplate,
    flowWishlistTemplate,
    flowCartTemplate,
    flowDeliveryTemplate,
    flowReviewsTemplate,
    flowRewardsTemplate,
    flowFinaleTemplate,
  ],
  designTokens,
  tags: [
    "ecommerce",
    "shopping",
    "flow",
    "continuous",
    "cinematic",
    "ribbon",
    "premium",
    "angled",
    "creative",
    "10-preview",
  ],
};

export const ecommerceShowcaseTemplates = [
  flowEntryTemplate,
  flowContinueTemplate,
  flowCategoriesTemplate,
  flowDealsTemplate,
  flowWishlistTemplate,
  flowCartTemplate,
  flowDeliveryTemplate,
  flowReviewsTemplate,
  flowRewardsTemplate,
  flowFinaleTemplate,
];
