import type { TemplateSet, PreviewTemplate } from "@/types";
import { CANVAS_WIDTH, CANVAS_HEIGHT } from "../placeholders";

// Design tokens for Luxury Shop - Premium, warm, conversion-focused
// Inspired by SHEIN's burgundy luxury + Temu's energetic warmth
const designTokens = {
  primaryColor: "#ffffff",
  secondaryColor: "rgba(255, 255, 255, 0.9)",
  accentColor: "#f5d4c1", // Warm cream/rose gold
  luxuryRed: "#8b1538", // Deep burgundy
  fontFamily: "system-ui, -apple-system, sans-serif",
};

// Preview 1: Luxury Hero - Premium opening with dramatic lighting
const luxuryHeroTemplate: PreviewTemplate = {
  id: "lux-hero",
  name: "Luxury Hero",
  description: "Premium hero with dramatic lighting effect",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(165deg, #1a0a0f 0%, #3d1522 25%, #5c1f32 50%, #3d1522 75%, #1a0a0f 100%)",
  placeholders: [
    {
      id: "luxury-hero-screenshot",
      name: "Main Screenshot",
      url: "/placeholders/screenshots/app-home.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Decorative top accent line
      {
        type: "rect",
        left: CANVAS_WIDTH / 2,
        top: 105,
        width: 180,
        height: 6,
        fill: designTokens.accentColor,
        originX: "center",
        originY: "center",
        rx: 3,
        ry: 3,
      },
      // Premium badge
      {
        type: "textbox",
        text: "EXCLUSIVE DEALS",
        fontSize: 26,
        fontWeight: "600",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.accentColor,
        left: CANVAS_WIDTH / 2,
        top: 150,
        width: 600,
        textAlign: "center",
        originX: "center",
        originY: "top",
        charSpacing: 350,
      },
      // Main headline - dramatic
      {
        type: "textbox",
        text: "Shop the Latest Trends",
        fontSize: 110,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: CANVAS_WIDTH / 2,
        top: 240,
        width: 1100,
        textAlign: "center",
        originX: "center",
        originY: "top",
        lineHeight: 1.1,
      },
      // Subheadline with warm accent
      {
        type: "textbox",
        text: "Up to 70% off everything",
        fontSize: 55,
        fontWeight: "500",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.accentColor,
        left: CANVAS_WIDTH / 2,
        top: 495,
        width: 1000,
        textAlign: "center",
        originX: "center",
        originY: "top",
      },
      // Screenshot with luxury glow
      {
        type: "image",
        src: "/placeholders/screenshots/app-home.svg",
        left: CANVAS_WIDTH / 2,
        top: 1630,
        scaleX: 1.7,
        scaleY: 1.7,
        angle: 0,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(245, 212, 193, 0.35)",
          blur: 200,
          offsetX: 0,
          offsetY: 0,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "luxury-hero-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 2: Flash Sale - Urgency focused
const flashSaleTemplate: PreviewTemplate = {
  id: "lux-flash-sale",
  name: "Flash Sale",
  description: "Urgency-focused flash sale design",
  category: "feature-callout",
  deviceType: "both",
  background: "linear-gradient(180deg, #ff6b35 0%, #f7931e 50%, #ff6b35 100%)",
  placeholders: [
    {
      id: "flash-sale-screenshot",
      name: "Sale Screenshot",
      url: "/placeholders/screenshots/app-dashboard.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Timer icon placeholder (circle)
      {
        type: "circle",
        left: CANVAS_WIDTH / 2,
        top: 165,
        radius: 54,
        fill: "rgba(255,255,255,0.2)",
        stroke: "#ffffff",
        strokeWidth: 6,
        originX: "center",
        originY: "center",
      },
      // Urgency headline
      {
        type: "textbox",
        text: "Flash Sale",
        fontSize: 140,
        fontWeight: "900",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: CANVAS_WIDTH / 2,
        top: 270,
        width: 1150,
        textAlign: "center",
        originX: "center",
        originY: "top",
        lineHeight: 1.0,
      },
      // Time remaining
      {
        type: "textbox",
        text: "Ends in 02:34:56",
        fontSize: 52,
        fontWeight: "600",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.95)",
        left: CANVAS_WIDTH / 2,
        top: 470,
        width: 900,
        textAlign: "center",
        originX: "center",
        originY: "top",
      },
      // Screenshot angled for energy
      {
        type: "image",
        src: "/placeholders/screenshots/app-dashboard.svg",
        left: CANVAS_WIDTH / 2,
        top: 1630,
        scaleX: 1.65,
        scaleY: 1.65,
        angle: -6,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(0,0,0,0.4)",
          blur: 130,
          offsetX: 40,
          offsetY: 65,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "flash-sale-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 3: Categories - Browse experience
const categoriesTemplate: PreviewTemplate = {
  id: "lux-categories",
  name: "Browse Categories",
  description: "Showcase category browsing",
  category: "feature-callout",
  deviceType: "both",
  background: "#0f0f0f",
  placeholders: [
    {
      id: "categories-screenshot",
      name: "Categories Screenshot",
      url: "/placeholders/screenshots/app-profile.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Category pills (decorative)
      {
        type: "rect",
        left: 90,
        top: 165,
        width: 210,
        height: 82,
        rx: 41,
        ry: 41,
        fill: "rgba(139, 21, 56, 0.8)",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Fashion",
        fontSize: 28,
        fontWeight: "500",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: 195,
        top: 186,
        width: 210,
        textAlign: "center",
        originX: "center",
        originY: "top",
      },
      {
        type: "rect",
        left: 330,
        top: 165,
        width: 180,
        height: 82,
        rx: 41,
        ry: 41,
        fill: "rgba(255,255,255,0.1)",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Home",
        fontSize: 28,
        fontWeight: "500",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.7)",
        left: 420,
        top: 186,
        width: 180,
        textAlign: "center",
        originX: "center",
        originY: "top",
      },
      {
        type: "rect",
        left: 540,
        top: 165,
        width: 195,
        height: 82,
        rx: 41,
        ry: 41,
        fill: "rgba(255,255,255,0.1)",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "Beauty",
        fontSize: 28,
        fontWeight: "500",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.7)",
        left: 637,
        top: 186,
        width: 195,
        textAlign: "center",
        originX: "center",
        originY: "top",
      },
      // Main headline
      {
        type: "textbox",
        text: "Millions of Products",
        fontSize: 115,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: 90,
        top: 320,
        width: 880,
        textAlign: "left",
        originX: "left",
        originY: "top",
        lineHeight: 1.1,
      },
      // Description
      {
        type: "textbox",
        text: "Find exactly what you're looking for",
        fontSize: 46,
        fontWeight: "400",
        fontFamily: designTokens.fontFamily,
        fill: "rgba(255,255,255,0.7)",
        left: 90,
        top: 600,
        width: 730,
        textAlign: "left",
        originX: "left",
        originY: "top",
        lineHeight: 1.4,
      },
      // Screenshot - angled right
      {
        type: "image",
        src: "/placeholders/screenshots/app-profile.svg",
        left: CANVAS_WIDTH / 2 + 90,
        top: 1650,
        scaleX: 1.6,
        scaleY: 1.6,
        angle: -8,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(139, 21, 56, 0.3)",
          blur: 130,
          offsetX: 25,
          offsetY: 50,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "categories-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Preview 4: Free Shipping - Trust builder
const freeShippingTemplate: PreviewTemplate = {
  id: "lux-shipping",
  name: "Free Shipping",
  description: "Highlight free shipping benefit",
  category: "feature-callout",
  deviceType: "both",
  background: "linear-gradient(145deg, #1a3a2f 0%, #0d4f3c 50%, #0a3d2e 100%)",
  placeholders: [
    {
      id: "shipping-screenshot",
      name: "Shipping Screenshot",
      url: "/placeholders/screenshots/app-list.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Screenshot - left side
      {
        type: "image",
        src: "/placeholders/screenshots/app-list.svg",
        left: 340,
        top: 1530,
        scaleX: 1.45,
        scaleY: 1.45,
        angle: 10,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(16, 185, 129, 0.25)",
          blur: 100,
          offsetX: -25,
          offsetY: 40,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "shipping-screenshot",
          replacementSlot: "primary",
        },
      },
      // Free badge
      {
        type: "rect",
        left: 728,
        top: 540,
        width: 150,
        height: 70,
        rx: 12,
        ry: 12,
        fill: "#10b981",
        originX: "left",
        originY: "top",
      },
      {
        type: "textbox",
        text: "FREE",
        fontSize: 28,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: "#ffffff",
        left: 803,
        top: 555,
        width: 150,
        textAlign: "center",
        originX: "center",
        originY: "top",
      },
      // Feature headline
      {
        type: "textbox",
        text: "Free Express Shipping",
        fontSize: 95,
        fontWeight: "700",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: 728,
        top: 660,
        width: 530,
        textAlign: "left",
        originX: "left",
        originY: "top",
        lineHeight: 1.15,
      },
      // Feature description
      {
        type: "textbox",
        text: "On orders over $49. Delivered in 2-5 days.",
        fontSize: 42,
        fontWeight: "400",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.secondaryColor,
        left: 728,
        top: 1030,
        width: 510,
        textAlign: "left",
        originX: "left",
        originY: "top",
        lineHeight: 1.4,
      },
    ],
  },
};

// Preview 5: Download CTA - Final conversion
const shopCtaTemplate: PreviewTemplate = {
  id: "lux-cta",
  name: "Shop Now CTA",
  description: "Conversion-focused final screen",
  category: "device-showcase",
  deviceType: "both",
  background: "linear-gradient(180deg, #1a0a0f 0%, #3d1522 40%, #5c1f32 70%, #3d1522 100%)",
  placeholders: [
    {
      id: "shop-cta-screenshot",
      name: "App Screenshot",
      url: "/placeholders/screenshots/app-home.svg",
      slot: "primary",
    },
  ],
  canvasJson: {
    version: "6.0.0",
    objects: [
      // Rating stars (simplified as text)
      {
        type: "textbox",
        text: "★★★★★",
        fontSize: 40,
        fontWeight: "400",
        fontFamily: designTokens.fontFamily,
        fill: "#fbbf24",
        left: CANVAS_WIDTH / 2,
        top: 135,
        width: 450,
        textAlign: "center",
        originX: "center",
        originY: "top",
        charSpacing: 100,
      },
      // Social proof
      {
        type: "textbox",
        text: "50M+ Happy Shoppers",
        fontSize: 30,
        fontWeight: "500",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.accentColor,
        left: CANVAS_WIDTH / 2,
        top: 210,
        width: 750,
        textAlign: "center",
        originX: "center",
        originY: "top",
      },
      // Main CTA headline
      {
        type: "textbox",
        text: "Start Shopping Today",
        fontSize: 115,
        fontWeight: "800",
        fontFamily: designTokens.fontFamily,
        fill: designTokens.primaryColor,
        left: CANVAS_WIDTH / 2,
        top: 300,
        width: 1100,
        textAlign: "center",
        originX: "center",
        originY: "top",
        lineHeight: 1.1,
      },
      // Value prop
      {
        type: "textbox",
        text: "New users get 30% off first order",
        fontSize: 46,
        fontWeight: "500",
        fontFamily: designTokens.fontFamily,
        fill: "#22c55e",
        left: CANVAS_WIDTH / 2,
        top: 570,
        width: 1000,
        textAlign: "center",
        originX: "center",
        originY: "top",
      },
      // Screenshot with premium glow
      {
        type: "image",
        src: "/placeholders/screenshots/app-home.svg",
        left: CANVAS_WIDTH / 2,
        top: 1630,
        scaleX: 1.7,
        scaleY: 1.7,
        angle: 0,
        originX: "center",
        originY: "center",
        shadow: {
          color: "rgba(245, 212, 193, 0.4)",
          blur: 175,
          offsetX: 0,
          offsetY: 0,
        },
        data: {
          isPlaceholder: true,
          placeholderId: "shop-cta-screenshot",
          replacementSlot: "primary",
        },
      },
    ],
  },
};

// Complete Luxury Shop set
export const luxuryShopSet: TemplateSet = {
  id: "luxury-shop",
  name: "Luxury Shop",
  description: "Premium 5-screenshot set inspired by top shopping apps like SHEIN & Temu",
  category: "feature-focused",
  appStoreCategories: ["shopping", "ecommerce"],
  deviceType: "both",
  previewCount: 5,
  templates: [
    luxuryHeroTemplate,
    flashSaleTemplate,
    categoriesTemplate,
    freeShippingTemplate,
    shopCtaTemplate,
  ],
  designTokens,
  tags: ["luxury", "shopping", "ecommerce", "premium", "fashion", "retail", "deals"],
};

export const luxuryShopTemplates = [
  luxuryHeroTemplate,
  flashSaleTemplate,
  categoriesTemplate,
  freeShippingTemplate,
  shopCtaTemplate,
];
